#common configuration shared between all applications
configserver:
  name: JHipster Registry Config Server
  status: Connected to the JHipster Registry Config Server

jhipster:
  logging:
    logstash: # forward logs to ELK
      enabled: false
      host: localhost
  metrics:
    logs: # report metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds

management:
  metrics:
    export:
      prometheus:
        enabled: false
spring:
  zipkin:
    base-url: http://34.66.65.247:9411
    enabled: false
  sleuth:
    sampler:
      probability: 1 # report 100% of traces to Zipkin
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@34.66.65.247:8761/eureka/
kafka:
  bootstrap-servers: 34.122.103.232:9092
  consumer:
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group.id: demo-1
    auto.offset.reset: earliest
  producer:
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: org.apache.kafka.common.serialization.StringSerializer
