#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MWQ2M2YwZjhjMWZiZjRiYTcwY2MwZjQxNmI4M2QzYTdmMzAxMDBlNzBjNjY2OGE4MTI5NjY5Yzk1M2QxMDI4YjJkOTdiOWQ0NmUzZGUwZWZmMzE5YzNkZWY5NjkwYjMzNGE4OA==
        token-validity-in-seconds: 2592000
        token-validity-in-seconds-for-remember-me: 2592000
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@35.202.39.145:8761/eureka/
