#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MWQ2M2YwZjhjMWZiZjRiYTcwY2MwZjQxNmI4M2QzYTdmMzAxMDBlNzBjNjY2OGE4MTI5NjY5Yzk1M2QxMDI4YjJkOTdiOWQ0NmUzZGUwZWZmMzE5YzNkZWY5NjkwYjMzNGE4OA==
        token-validity-in-seconds: 2592000
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: 104.197.164.153
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

management:
  metrics:
    export:
      prometheus:
        enabled: false
spring:
  zipkin:
    base-url: http://104.197.164.153:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1 # report 100% of traces to Zipkin
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@104.197.164.153:8761/eureka/
